name: Deploy to EC2  # 이 워크플로우의 이름. GitHub Actions 탭에 표시됨

on:
  push:
    branches: [ "main" ]  # main 브랜치에 push될 때만 이 워크플로우가 실행됨

jobs:
  deploy:
    runs-on: ubuntu-latest  # GitHub Actions가 사용하는 가상 머신 환경 (우분투 최신 버전)

    steps:
      - name: Checkout
        uses: actions/checkout@v4  # 현재 저장소의 코드를 가져옴 (필수 단계)

      - name: Set up JDK
        uses: actions/setup-java@v4  # Java 빌드 환경을 설정함
        with:
          distribution: 'temurin'
          java-version: '17'  # Java 17 버전을 사용함 (Dockerfile과 일치해야 함)

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Build
        run: ./gradlew clean build -x test  # Gradle로 프로젝트를 빌드함. 테스트는 제외 (-x test)

      - name: Login to ECR
        uses: aws-actions/amazon-ecr-login@v1  # ECR에 로그인. 이후 Docker push를 하기 위함
        env:
          AWS_REGION: ap-northeast-2
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - name: Build and Push Docker Image
        run: |
          IMAGE_URI={888042016323.dkr.ecr.ap-southeast-2.amazonaws.com/namespace/unis}:latest  # 사용할 Docker 이미지 태그 정의
          docker build -t $IMAGE_URI .  # 현재 디렉토리(.)에 있는 Dockerfile을 기준으로 이미지 빌드
          docker push $IMAGE_URI  # 빌드한 이미지를 ECR에 push (업로드)

      - name: SSH into EC2 and Deploy
        uses: appleboy/ssh-action@v1.0.0  # EC2에 SSH로 접속하여 명령어를 실행하기 위한 액션
        with:
          host: ${{ secrets.EC2_HOST }}  # EC2 접속 주소 (ex. ec2-user@<퍼블릭 IP>)
          username: ec2-user  # Amazon Linux 기본 사용자명
          key: ${{ secrets.EC2_KEY }}  # base64로 인코딩된 pem 키 (GitHub Secrets에 등록된 값)
          script: |
            aws ecr get-login-password --region ap-northeast-2 | \
            docker login --username AWS --password-stdin 888042016323.dkr.ecr.ap-southeast-2.amazonaws.com/namespace/unis 
            docker pull 888042016323.dkr.ecr.ap-southeast-2.amazonaws.com/namespace/unis:latest
            docker stop app || true && docker rm app || true
            docker run -d --name app -p 8080:8080 888042016323.dkr.ecr.ap-southeast-2.amazonaws.com/namespace/unis:latest